#!/usr/bin/env python3
"""Write the LaTeX tables of the neutral-label analysis from results.json."""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "results" / "tables"
R = json.loads((HERE / "results.json").read_text())
W1 = R["windows"]["W1_registered_jun_aug_2026"]
W0 = R["windows"]["W0_spring_mar_may_2026"]

NAMES = {
    "P": "In-approve degree minus transfer in-degree",
    "Q": "EndorseRank (activity restarts) minus AWP",
    "L1-L0": "C-PR ($\\lambda=1$) minus C-PR ($\\lambda=0$)",
    "ER-AWP": "EndorseRank minus AWP",
    "L0-AWP": "C-PR ($\\lambda=0$) minus AWP",
    "ER-deg": "EndorseRank minus in-approve degree",
    "CPR-deg": "C-PR ($\\lambda=0.5$) minus in-approve degree",
}
LABEL_NAMES = {
    "future_liquidation_free_rate": "Liquidation-free close rate",
    "future_zero_liquidation": "No liquidation",
    "close_success_count": "Profitable closes",
    "realized_gain_proxy": "Realized gain",
    "close_success_rate": "Profitable share",
    "non_loss_close_rate": "Non-loss share",
}


def f(x: float | None) -> str:
    if x is None:
        return "--"
    return f"{x:+.3f}".replace("+", "") if x >= 0 else f"{x:.3f}"


def iv(pair: list) -> str:
    return f"[{f(pair[0])}, {f(pair[1])}]"


def contrasts_table() -> str:
    lab = "future_liquidation_free_rate"
    rows = []
    for wname, w in (("Registered window, June--August 2026", W1), ("Spring window, March--May 2026", W0)):
        res = w["plain"][lab]
        st = w["stratified_by_closes"][lab]["contrasts"]
        rows.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{{wname} ($n={res['n']:,}$ traders)}}}} \\\\".replace(f"{res['n']:,}", f"{res['n']:,}".replace(",", "{,}")))
        for cid in ("P", "Q", "L1-L0", "ER-AWP", "L0-AWP", "ER-deg"):
            c = res["contrasts"][cid]
            c975 = iv(c["ci975"]) if cid in ("P", "Q") else "--"
            rows.append(
                f"{NAMES[cid]} & {f(c['tau_a'])} & {f(c['tau_b'])} & {f(c['delta'])} & {iv(c['ci95'])} & {c975} \\\\"
            )
        for cid in ("P", "Q"):
            c = st[cid]
            rows.append(
                f"\\quad {NAMES[cid]}, stratified by closes & {f(c['tau_a'])} & {f(c['tau_b'])} & {f(c['delta'])} & {iv(c['ci95'])} & -- \\\\"
            )
        rows.append("\\midrule")
    rows = rows[:-1]
    body = "\n".join(rows)
    return f"""% Generated by analysis/neutral-label/export_tables.py from analysis/neutral-label/results.json.
\\begin{{table}}[htbp]
\\centering
\\caption[Allowance-side against transfer-side scores on the liquidation-free close rate (pre-specified post hoc analysis).]{{Allowance-side against transfer-side scores on the liquidation-free close rate of the matched traders with at least three closes in the label window, a label built from neither edge type. The analysis plan, contrasts and decision rules were committed on 9~October~2026 before any of these numbers were computed, after the registered labels were known, so every row is a pre-specified post hoc result. Paired wallet bootstrap with {R['n_boot']:,} resamples (seed {R['seed']}); the 97.5\\% intervals are the Bonferroni intervals of the two decision contrasts. The stratified rows combine Kendall's $\\tau_b$ within strata of the number of label-window closes (3--4, 5--9, 10--24, 25 or more), weighted by the number of wallet pairs.}}
\\label{{tab:neutral-label-contrasts}}
\\fitwidth{{%
\\begin{{tabular}}{{lccccc}}
\\toprule
Contrast ($a$ minus $b$) & $\\tau_a$ & $\\tau_b$ & $\\Delta\\tau$ & 95\\% CI & 97.5\\% CI \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
}}
\\end{{table}}
""".replace(f"{R['n_boot']:,}", "{:,}".format(R["n_boot"]).replace(",", "{,}"))


def grid_table() -> str:
    rows = []
    for wname, w in (("Registered window, June--August 2026", W1), ("Spring window, March--May 2026", W0)):
        rows.append(f"\\multicolumn{{5}}{{l}}{{\\emph{{{wname}}}}} \\\\")
        for lab, lname in LABEL_NAMES.items():
            if lab not in w["plain"]:
                continue
            cells = []
            for cid in ("P", "Q", "L1-L0", "ER-AWP"):
                c = w["plain"][lab]["contrasts"][cid]
                cells.append(f"\\begin{{tabular}}[c]{{@{{}}c@{{}}}}{f(c['delta'])}\\\\[-1pt]{{\\footnotesize {iv(c['ci95'])}}}\\end{{tabular}}")
            rows.append(f"{lname} & " + " & ".join(cells) + " \\\\")
        rows.append("\\midrule")
    rows = rows[:-1]
    body = "\n".join(rows)
    return f"""% Generated by analysis/neutral-label/export_tables.py from analysis/neutral-label/results.json.
\\begin{{table}}[htbp]
\\centering
\\caption[Allowance-side minus transfer-side scores on every trader label in both windows.]{{Allowance-side minus transfer-side scores, $\\Delta\\tau$ with 95\\% paired bootstrap interval, on all six trader labels of the registered window and of the spring window (pre-specified post hoc analysis; Section~\\ref{{sub:neutral-label-results}}). P: in-approve degree minus transfer in-degree. Q: EndorseRank with activity restarts minus AWP (same edge weights and restart rule). C-PR: $\\lambda=1$ minus $\\lambda=0$ (same raw-amount build). ER: EndorseRank minus AWP. Profitable closes and realized gain grow with the number of closes; the other four labels do not.}}
\\label{{tab:neutral-label-grid}}
\\fitwidth{{%
\\begin{{tabular}}{{lcccc}}
\\toprule
Label & P (counts) & Q (PageRanks) & C-PR layers & ER minus AWP \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
}}
\\end{{table}}
"""


def recipients_table() -> str:
    rows = []
    for wname, w in (("Registered window, June--August 2026", W1), ("Spring window, March--May 2026", W0)):
        r = w["recipients"]
        cls = r["recipient_account_classes"]
        cls_s = ", ".join(f"{v} {(k.upper() if k == 'eoa' else k)}" for k, v in sorted(cls.items(), key=lambda kv: -kv[1]))
        rd = r["zero_liquidation_risk_difference"]
        rows.append(f"\\multicolumn{{3}}{{l}}{{\\emph{{{wname} ($n={r['n_labelled']:,}$ labelled traders)}}}} \\\\".replace(f"{r['n_labelled']:,}", f"{r['n_labelled']:,}".replace(",", "{,}")))
        a, b = r["recipients"], r["non_recipients"]
        rows.append(f"Traders & {a['n']} & {b['n']:,} \\\\".replace(",", "{,}"))
        rows.append(f"Share with no liquidation & {a['zero_liquidation_share']:.3f} & {b['zero_liquidation_share']:.3f} \\\\")
        rows.append(f"Mean liquidation-free close rate & {a['mean_lfcr']:.3f} & {b['mean_lfcr']:.3f} \\\\")
        rows.append(f"Mean profitable share & {a['mean_profitable_share']:.3f} & {b['mean_profitable_share']:.3f} \\\\")
        rows.append(f"Mean non-loss share & {a['mean_non_loss_share']:.3f} & {b['mean_non_loss_share']:.3f} \\\\")
        rows.append(f"Median closes in the label window & {a['median_closes']:.1f} & {b['median_closes']:.1f} \\\\")
        rows.append(f"\\multicolumn{{3}}{{l}}{{Risk difference in no liquidation: {f(rd['point'])} {iv(rd['ci95'])}; recipients by account type: {cls_s}}} \\\\")
        p = r["P_without_top10_recipients"]
        rows.append(f"\\multicolumn{{3}}{{l}}{{P without the 10 recipients of highest in-approve degree: {f(p['delta'])} {iv(p['ci95'])}}} \\\\")
        rows.append("\\midrule")
    rows = rows[:-1]
    body = "\n".join(rows)
    return f"""% Generated by analysis/neutral-label/export_tables.py from analysis/neutral-label/results.json.
\\begin{{table}}[htbp]
\\centering
\\caption[Traders that receive approvals against all other labelled traders.]{{Labelled traders with a positive in-approve degree at the freeze (recipients) against all other labelled traders (pre-specified post hoc analysis). Account types come from the code lookup of the spring spender cohort; a recipient that was not in that cohort is \\emph{{unknown}}. Bootstrap intervals use the resamples of Table~\\ref{{tab:neutral-label-contrasts}}.}}
\\label{{tab:neutral-label-recipients}}
\\fitwidth{{%
\\begin{{tabular}}{{lcc}}
\\toprule
 & Recipients & Other traders \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
}}
\\end{{table}}
"""


def main() -> int:
    (OUT / "neutral-label-contrasts.tex").write_text(contrasts_table())
    (OUT / "neutral-label-grid.tex").write_text(grid_table())
    (OUT / "neutral-label-recipients.tex").write_text(recipients_table())
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
